inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'Vagrantfile'
    - 'vendor/**/*'
    - 'exe/**/*'
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/AbcSize:
  Exclude:
    - 'test/test_helper.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'test/**/*.rb'

Layout/LineLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
