sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
before_install: gem install bundler -v 1.15.3
script:
  - bundle exec rake
  - bash <(curl -fsSL https://github.com/everypolitician/ensure-regression-tests/raw/master/ensure-regression-tests)
